"""empty message

Revision ID: 489cf746b500
Revises: None
Create Date: 2015-11-20 17:18:29.015000

"""

# revision identifiers, used by Alembic.
revision = '489cf746b500'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('phone_number', sa.String(), nullable=False),
        sa.Column('country_code', sa.String(), nullable=False),
        sa.Column('phone_number_confirmed', sa.Boolean(), nullable=False),
        sa.Column('authy_user_id', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
